<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'أفغانستان', 'code' => 'AF'],
            ['name' => 'ألبانيا', 'code' => 'AL'],
            ['name' => 'الجزائر', 'code' => 'DZ'],
            ['name' => 'أندورا', 'code' => 'AD'],
            ['name' => 'أنغولا', 'code' => 'AO'],
            ['name' => 'أنتيغوا وباربودا', 'code' => 'AG'],
            ['name' => 'الأرجنتين', 'code' => 'AR'],
            ['name' => 'أرمينيا', 'code' => 'AM'],
            ['name' => 'أستراليا', 'code' => 'AU'],
            ['name' => 'النمسا', 'code' => 'AT'],
            ['name' => 'أذربيجان', 'code' => 'AZ'],
            ['name' => 'جزر البهاما', 'code' => 'BS'],
            ['name' => 'البحرين', 'code' => 'BH'],
            ['name' => 'بنغلاديش', 'code' => 'BD'],
            ['name' => 'بربادوس', 'code' => 'BB'],
            ['name' => 'بيلاروسيا', 'code' => 'BY'],
            ['name' => 'بلجيكا', 'code' => 'BE'],
            ['name' => 'بليز', 'code' => 'BZ'],
            ['name' => 'بنين', 'code' => 'BJ'],
            ['name' => 'بوتان', 'code' => 'BT'],
            ['name' => 'بوليفيا', 'code' => 'BO'],
            ['name' => 'البوسنة والهرسك', 'code' => 'BA'],
            ['name' => 'بوتسوانا', 'code' => 'BW'],
            ['name' => 'البرازيل', 'code' => 'BR'],
            ['name' => 'بروناي', 'code' => 'BN'],
            ['name' => 'بلغاريا', 'code' => 'BG'],
            ['name' => 'بوركينا فاسو', 'code' => 'BF'],
            ['name' => 'بوروندي', 'code' => 'BI'],
            ['name' => 'الرأس الأخضر', 'code' => 'CV'],
            ['name' => 'كمبوديا', 'code' => 'KH'],
            ['name' => 'الكاميرون', 'code' => 'CM'],
            ['name' => 'كندا', 'code' => 'CA'],
            ['name' => 'جمهورية أفريقيا الوسطى', 'code' => 'CF'],
            ['name' => 'تشاد', 'code' => 'TD'],
            ['name' => 'تشيلي', 'code' => 'CL'],
            ['name' => 'الصين', 'code' => 'CN'],
            ['name' => 'كولومبيا', 'code' => 'CO'],
            ['name' => 'جزر القمر', 'code' => 'KM'],
            ['name' => 'جمهورية الكونغو', 'code' => 'CG'],
            ['name' => 'جمهورية الكونغو الديمقراطية', 'code' => 'CD'],
            ['name' => 'كوستاريكا', 'code' => 'CR'],
            ['name' => 'ساحل العاج', 'code' => 'CI'],
            ['name' => 'كرواتيا', 'code' => 'HR'],
            ['name' => 'كوبا', 'code' => 'CU'],
            ['name' => 'قبرص', 'code' => 'CY'],
            ['name' => 'التشيك', 'code' => 'CZ'],
            ['name' => 'الدنمارك', 'code' => 'DK'],
            ['name' => 'جيبوتي', 'code' => 'DJ'],
            ['name' => 'دومينيكا', 'code' => 'DM'],
            ['name' => 'جمهورية الدومينيكان', 'code' => 'DO'],
            ['name' => 'الإكوادور', 'code' => 'EC'],
            ['name' => 'مصر', 'code' => 'EG'],
            ['name' => 'السلفادور', 'code' => 'SV'],
            ['name' => 'غينيا الاستوائية', 'code' => 'GQ'],
            ['name' => 'إريتريا', 'code' => 'ER'],
            ['name' => 'إستونيا', 'code' => 'EE'],
            ['name' => 'إسواتيني', 'code' => 'SZ'],
            ['name' => 'إثيوبيا', 'code' => 'ET'],
            ['name' => 'فيجي', 'code' => 'FJ'],
            ['name' => 'فنلندا', 'code' => 'FI'],
            ['name' => 'فرنسا', 'code' => 'FR'],
            ['name' => 'الغابون', 'code' => 'GA'],
            ['name' => 'غامبيا', 'code' => 'GM'],
            ['name' => 'جورجيا', 'code' => 'GE'],
            ['name' => 'ألمانيا', 'code' => 'DE'],
            ['name' => 'غانا', 'code' => 'GH'],
            ['name' => 'اليونان', 'code' => 'GR'],
            ['name' => 'غرينادا', 'code' => 'GD'],
            ['name' => 'غواتيمالا', 'code' => 'GT'],
            ['name' => 'غينيا', 'code' => 'GN'],
            ['name' => 'غينيا بيساو', 'code' => 'GW'],
            ['name' => 'غيانا', 'code' => 'GY'],
            ['name' => 'هايتي', 'code' => 'HT'],
            ['name' => 'هندوراس', 'code' => 'HN'],
            ['name' => 'المجر', 'code' => 'HU'],
            ['name' => 'آيسلندا', 'code' => 'IS'],
            ['name' => 'الهند', 'code' => 'IN'],
            ['name' => 'إندونيسيا', 'code' => 'ID'],
            ['name' => 'إيران', 'code' => 'IR'],
            ['name' => 'العراق', 'code' => 'IQ'],
            ['name' => 'أيرلندا', 'code' => 'IE'],
            ['name' => 'إسرائيل', 'code' => 'IL'],
            ['name' => 'إيطاليا', 'code' => 'IT'],
            ['name' => 'جامايكا', 'code' => 'JM'],
            ['name' => 'اليابان', 'code' => 'JP'],
            ['name' => 'الأردن', 'code' => 'JO'],
            ['name' => 'كازاخستان', 'code' => 'KZ'],
            ['name' => 'كينيا', 'code' => 'KE'],
            ['name' => 'كيريباتي', 'code' => 'KI'],
            ['name' => 'الكويت', 'code' => 'KW'],
            ['name' => 'قيرغيزستان', 'code' => 'KG'],
            ['name' => 'لاوس', 'code' => 'LA'],
            ['name' => 'لاتفيا', 'code' => 'LV'],
            ['name' => 'لبنان', 'code' => 'LB'],
            ['name' => 'ليسوتو', 'code' => 'LS'],
            ['name' => 'ليبيريا', 'code' => 'LR'],
            ['name' => 'ليبيا', 'code' => 'LY'],
            ['name' => 'ليختنشتاين', 'code' => 'LI'],
            ['name' => 'ليتوانيا', 'code' => 'LT'],
            ['name' => 'لوكسمبورغ', 'code' => 'LU'],
            ['name' => 'مدغشقر', 'code' => 'MG'],
            ['name' => 'مالاوي', 'code' => 'MW'],
            ['name' => 'ماليزيا', 'code' => 'MY'],
            ['name' => 'جزر المالديف', 'code' => 'MV'],
            ['name' => 'مالي', 'code' => 'ML'],
            ['name' => 'مالطا', 'code' => 'MT'],
            ['name' => 'جزر مارشال', 'code' => 'MH'],
            ['name' => 'موريتانيا', 'code' => 'MR'],
            ['name' => 'موريشيوس', 'code' => 'MU'],
            ['name' => 'المكسيك', 'code' => 'MX'],
            ['name' => 'ولايات ميكرونيسيا المتحدة', 'code' => 'FM'],
            ['name' => 'مولدوفا', 'code' => 'MD'],
            ['name' => 'موناكو', 'code' => 'MC'],
            ['name' => 'منغوليا', 'code' => 'MN'],
            ['name' => 'الجبل الأسود', 'code' => 'ME'],
            ['name' => 'المغرب', 'code' => 'MA'],
            ['name' => 'موزمبيق', 'code' => 'MZ'],
            ['name' => 'ميانمار', 'code' => 'MM'],
            ['name' => 'ناميبيا', 'code' => 'NA'],
            ['name' => 'ناورو', 'code' => 'NR'],
            ['name' => 'نيبال', 'code' => 'NP'],
            ['name' => 'هولندا', 'code' => 'NL'],
            ['name' => 'نيوزيلندا', 'code' => 'NZ'],
            ['name' => 'نيكاراغوا', 'code' => 'NI'],
            ['name' => 'النيجر', 'code' => 'NE'],
            ['name' => 'نيجيريا', 'code' => 'NG'],
            ['name' => 'كوريا الشمالية', 'code' => 'KP'],
            ['name' => 'مقدونيا الشمالية', 'code' => 'MK'],
            ['name' => 'النرويج', 'code' => 'NO'],
            ['name' => 'عُمان', 'code' => 'OM'],
            ['name' => 'باكستان', 'code' => 'PK'],
            ['name' => 'بالاو', 'code' => 'PW'],
            ['name' => 'فلسطين', 'code' => 'PS'],
            ['name' => 'بنما', 'code' => 'PA'],
            ['name' => 'بابوا غينيا الجديدة', 'code' => 'PG'],
            ['name' => 'باراغواي', 'code' => 'PY'],
            ['name' => 'بيرو', 'code' => 'PE'],
            ['name' => 'الفلبين', 'code' => 'PH'],
            ['name' => 'بولندا', 'code' => 'PL'],
            ['name' => 'البرتغال', 'code' => 'PT'],
            ['name' => 'قطر', 'code' => 'QA'],
            ['name' => 'رومانيا', 'code' => 'RO'],
            ['name' => 'روسيا', 'code' => 'RU'],
            ['name' => 'رواندا', 'code' => 'RW'],
            ['name' => 'سانت كيتس ونيفيس', 'code' => 'KN'],
            ['name' => 'سانت لوسيا', 'code' => 'LC'],
            ['name' => 'سانت فنسنت والغرينادين', 'code' => 'VC'],
            ['name' => 'ساموا', 'code' => 'WS'],
            ['name' => 'سان مارينو', 'code' => 'SM'],
            ['name' => 'ساو تومي وبرينسيبي', 'code' => 'ST'],
            ['name' => 'السعودية', 'code' => 'SA'],
            ['name' => 'السنغال', 'code' => 'SN'],
            ['name' => 'صربيا', 'code' => 'RS'],
            ['name' => 'سيشل', 'code' => 'SC'],
            ['name' => 'سيراليون', 'code' => 'SL'],
            ['name' => 'سنغافورة', 'code' => 'SG'],
            ['name' => 'سلوفاكيا', 'code' => 'SK'],
            ['name' => 'سلوفينيا', 'code' => 'SI'],
            ['name' => 'جزر سليمان', 'code' => 'SB'],
            ['name' => 'الصومال', 'code' => 'SO'],
            ['name' => 'جنوب أفريقيا', 'code' => 'ZA'],
            ['name' => 'كوريا الجنوبية', 'code' => 'KR'],
            ['name' => 'جنوب السودان', 'code' => 'SS'],
            ['name' => 'إسبانيا', 'code' => 'ES'],
            ['name' => 'سريلانكا', 'code' => 'LK'],
            ['name' => 'السودان', 'code' => 'SD'],
            ['name' => 'سورينام', 'code' => 'SR'],
            ['name' => 'السويد', 'code' => 'SE'],
            ['name' => 'سويسرا', 'code' => 'CH'],
            ['name' => 'سوريا', 'code' => 'SY'],
            ['name' => 'طاجيكستان', 'code' => 'TJ'],
            ['name' => 'تنزانيا', 'code' => 'TZ'],
            ['name' => 'تايلاند', 'code' => 'TH'],
            ['name' => 'تيمور الشرقية', 'code' => 'TL'],
            ['name' => 'توغو', 'code' => 'TG'],
            ['name' => 'تونغا', 'code' => 'TO'],
            ['name' => 'ترينيداد وتوباغو', 'code' => 'TT'],
            ['name' => 'تونس', 'code' => 'TN'],
            ['name' => 'تركيا', 'code' => 'TR'],
            ['name' => 'تركمانستان', 'code' => 'TM'],
            ['name' => 'توفالو', 'code' => 'TV'],
            ['name' => 'أوغندا', 'code' => 'UG'],
            ['name' => 'أوكرانيا', 'code' => 'UA'],
            ['name' => 'الإمارات العربية المتحدة', 'code' => 'AE'],
            ['name' => 'المملكة المتحدة', 'code' => 'GB'],
            ['name' => 'الولايات المتحدة', 'code' => 'US'],
            ['name' => 'أوروغواي', 'code' => 'UY'],
            ['name' => 'أوزبكستان', 'code' => 'UZ'],
            ['name' => 'فانواتو', 'code' => 'VU'],
            ['name' => 'الفاتيكان', 'code' => 'VA'],
            ['name' => 'فنزويلا', 'code' => 'VE'],
            ['name' => 'فيتنام', 'code' => 'VN'],
            ['name' => 'اليمن', 'code' => 'YE'],
            ['name' => 'زامبيا', 'code' => 'ZM'],
            ['name' => 'زيمبابوي', 'code' => 'ZW'],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->updateOrInsert(
                ['code' => $country['code']],
                [
                    'name' => $country['name'],
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }
}
