<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'أفغانستان - Afghanistan', 'code' => 'AF'],
            ['name' => 'ألبانيا - Albania', 'code' => 'AL'],
            ['name' => 'الجزائر - Algeria', 'code' => 'DZ'],
            ['name' => 'أندورا - Andorra', 'code' => 'AD'],
            ['name' => 'أنغولا - Angola', 'code' => 'AO'],
            ['name' => 'أنتيغوا وباربودا - Antigua and Barbuda', 'code' => 'AG'],
            ['name' => 'الأرجنتين - Argentina', 'code' => 'AR'],
            ['name' => 'أرمينيا - Armenia', 'code' => 'AM'],
            ['name' => 'أستراليا - Australia', 'code' => 'AU'],
            ['name' => 'النمسا - Austria', 'code' => 'AT'],
            ['name' => 'أذربيجان - Azerbaijan', 'code' => 'AZ'],
            ['name' => 'جزر البهاما - Bahamas', 'code' => 'BS'],
            ['name' => 'البحرين - Bahrain', 'code' => 'BH'],
            ['name' => 'بنغلاديش - Bangladesh', 'code' => 'BD'],
            ['name' => 'بربادوس - Barbados', 'code' => 'BB'],
            ['name' => 'بيلاروسيا - Belarus', 'code' => 'BY'],
            ['name' => 'بلجيكا - Belgium', 'code' => 'BE'],
            ['name' => 'بليز - Belize', 'code' => 'BZ'],
            ['name' => 'بنين - Boys', 'code' => 'BJ'],
            ['name' => 'بوتان - Bhutan', 'code' => 'BT'],
            ['name' => 'بوليفيا - Bolivia', 'code' => 'BO'],
            ['name' => 'البوسنة والهرسك - Bosnia and Herzegovina', 'code' => 'BA'],
            ['name' => 'بوتسوانا - Botswana', 'code' => 'BW'],
            ['name' => 'البرازيل - Brazil', 'code' => 'BR'],
            ['name' => 'بروناي - Brunei', 'code' => 'BN'],
            ['name' => 'بلغاريا - Bulgaria', 'code' => 'BG'],
            ['name' => 'بوركينا فاسو - Burkina Faso', 'code' => 'BF'],
            ['name' => 'بوروندي - Burundi', 'code' => 'BI'],
            ['name' => 'الرأس الأخضر - Cape Verde', 'code' => 'CV'],
            ['name' => 'كمبوديا - Cambodia', 'code' => 'KH'],
            ['name' => 'الكاميرون - Cameroon', 'code' => 'CM'],
            ['name' => 'كندا - Canada', 'code' => 'CA'],
            ['name' => 'جمهورية أفريقيا الوسطى - Central African Republic', 'code' => 'CF'],
            ['name' => 'تشاد - Chad', 'code' => 'TD'],
            ['name' => 'تشيلي - Chile', 'code' => 'CL'],
            ['name' => 'الصين - China', 'code' => 'CN'],
            ['name' => 'كولومبيا - Colombia', 'code' => 'CO'],
            ['name' => 'جزر القمر - Comoros', 'code' => 'KM'],
            ['name' => 'جمهورية الكونغو - Republic of the Congo', 'code' => 'CG'],
            ['name' => 'جمهورية الكونغو الديمقراطية - Democratic Republic of the Congo', 'code' => 'CD'],
            ['name' => 'كوستاريكا - Costa Rica', 'code' => 'CR'],
            ['name' => 'ساحل العاج - Ivory Coast', 'code' => 'CI'],
            ['name' => 'كرواتيا - Croatia', 'code' => 'HR'],
            ['name' => 'كوبا - Cuba', 'code' => 'CU'],
            ['name' => 'قبرص - Cyprus', 'code' => 'CY'],
            ['name' => 'التشيك - Czech Republic', 'code' => 'CZ'],
            ['name' => 'الدنمارك - Denmark', 'code' => 'DK'],
            ['name' => 'جيبوتي - Djibouti', 'code' => 'DJ'],
            ['name' => 'دومينيكا - Dominica', 'code' => 'DM'],
            ['name' => 'جمهورية الدومينيكان - Dominican Republic', 'code' => 'DO'],
            ['name' => 'الإكوادور - Ecuador', 'code' => 'EC'],
            ['name' => 'مصر - Egypt', 'code' => 'EG'],
            ['name' => 'السلفادور - El Salvador', 'code' => 'SV'],
            ['name' => 'غينيا الاستوائية - Equatorial Guinea', 'code' => 'GQ'],
            ['name' => 'إريتريا - Eritrea', 'code' => 'ER'],
            ['name' => 'إستونيا - Estonia', 'code' => 'EE'],
            ['name' => 'إسواتيني - Eswatini', 'code' => 'SZ'],
            ['name' => 'إثيوبيا - Ethiopia', 'code' => 'ET'],
            ['name' => 'فيجي - Fiji', 'code' => 'FJ'],
            ['name' => 'فنلندا - Finland', 'code' => 'FI'],
            ['name' => 'فرنسا - France', 'code' => 'FR'],
            ['name' => 'الغابون - Gabon', 'code' => 'GA'],
            ['name' => 'غامبيا - Gambia', 'code' => 'GM'],
            ['name' => 'جورجيا - Georgia', 'code' => 'GE'],
            ['name' => 'ألمانيا - Germany', 'code' => 'DE'],
            ['name' => 'غانا - Ghana', 'code' => 'GH'],
            ['name' => 'اليونان - Greece', 'code' => 'GR'],
            ['name' => 'غرينادا - Grenada', 'code' => 'GD'],
            ['name' => 'غواتيمالا - Guatemala', 'code' => 'GT'],
            ['name' => 'غينيا - Guinea', 'code' => 'GN'],
            ['name' => 'غينيا بيساو - Guinea Bissau', 'code' => 'GW'],
            ['name' => 'غيانا - Guyana', 'code' => 'GY'],
            ['name' => 'هايتي - Haiti', 'code' => 'HT'],
            ['name' => 'هندوراس - Honduras', 'code' => 'HN'],
            ['name' => 'المجر - Hungary', 'code' => 'HU'],
            ['name' => 'آيسلندا - Iceland', 'code' => 'IS'],
            ['name' => 'الهند - India', 'code' => 'IN'],
            ['name' => 'إندونيسيا - Indonesia', 'code' => 'ID'],
            ['name' => 'إيران - Iran', 'code' => 'IR'],
            ['name' => 'العراق - Iraq', 'code' => 'IQ'],
            ['name' => 'أيرلندا - Ireland', 'code' => 'IE'],
            ['name' => 'إسرائيل - Israel', 'code' => 'IL'],
            ['name' => 'إيطاليا - Italy', 'code' => 'IT'],
            ['name' => 'جامايكا - Jamaica', 'code' => 'JM'],
            ['name' => 'اليابان - Japan', 'code' => 'JP'],
            ['name' => 'الأردن - Jordan', 'code' => 'JO'],
            ['name' => 'كازاخستان - Kazakhstan', 'code' => 'KZ'],
            ['name' => 'كينيا - Kenya', 'code' => 'KE'],
            ['name' => 'كيريباتي - Kiribati', 'code' => 'KI'],
            ['name' => 'الكويت - Kuwait', 'code' => 'KW'],
            ['name' => 'قيرغيزستان - Kyrgyzstan', 'code' => 'KG'],
            ['name' => 'لاوس - Laos', 'code' => 'LA'],
            ['name' => 'لاتفيا - Latvia', 'code' => 'LV'],
            ['name' => 'لبنان - Lebanon', 'code' => 'LB'],
            ['name' => 'ليسوتو - Lesotho', 'code' => 'LS'],
            ['name' => 'ليبيريا - Liberia', 'code' => 'LR'],
            ['name' => 'ليبيا - Libya', 'code' => 'LY'],
            ['name' => 'ليختنشتاين - Liechtenstein', 'code' => 'LI'],
            ['name' => 'ليتوانيا - Lithuania', 'code' => 'LT'],
            ['name' => 'لوكسمبورغ - Luxembourg', 'code' => 'LU'],
            ['name' => 'مدغشقر - Madagascar', 'code' => 'MG'],
            ['name' => 'مالاوي - Malawi', 'code' => 'MW'],
            ['name' => 'ماليزيا - Malaysia', 'code' => 'MY'],
            ['name' => 'جزر المالديف - Maldives', 'code' => 'MV'],
            ['name' => 'مالي - My money', 'code' => 'ML'],
            ['name' => 'مالطا - Malta', 'code' => 'MT'],
            ['name' => 'جزر مارشال - Marshall Islands', 'code' => 'MH'],
            ['name' => 'موريتانيا - Mauritania', 'code' => 'MR'],
            ['name' => 'موريشيوس - Mauritius', 'code' => 'MU'],
            ['name' => 'المكسيك - Mexico', 'code' => 'MX'],
            ['name' => 'ولايات ميكرونيسيا المتحدة - Federated States of Micronesia', 'code' => 'FM'],
            ['name' => 'مولدوفا - Moldova', 'code' => 'MD'],
            ['name' => 'موناكو - Monaco', 'code' => 'MC'],
            ['name' => 'منغوليا - Mongolia', 'code' => 'MN'],
            ['name' => 'الجبل الأسود - Montenegro', 'code' => 'ME'],
            ['name' => 'المغرب - Morocco', 'code' => 'MA'],
            ['name' => 'موزمبيق - Mozambique', 'code' => 'MZ'],
            ['name' => 'ميانمار - Myanmar', 'code' => 'MM'],
            ['name' => 'ناميبيا - Namibia', 'code' => 'NA'],
            ['name' => 'ناورو - Nauru', 'code' => 'NR'],
            ['name' => 'نيبال - Nepal', 'code' => 'NP'],
            ['name' => 'هولندا - Netherlands', 'code' => 'NL'],
            ['name' => 'نيوزيلندا - New Zealand', 'code' => 'NZ'],
            ['name' => 'نيكاراغوا - Nicaragua', 'code' => 'NI'],
            ['name' => 'النيجر - Niger', 'code' => 'NE'],
            ['name' => 'نيجيريا - Nigeria', 'code' => 'NG'],
            ['name' => 'كوريا الشمالية - North Korea', 'code' => 'KP'],
            ['name' => 'مقدونيا الشمالية - North Macedonia', 'code' => 'MK'],
            ['name' => 'النرويج - Norway', 'code' => 'NO'],
            ['name' => 'عُمان - Oman', 'code' => 'OM'],
            ['name' => 'باكستان - Pakistan', 'code' => 'PK'],
            ['name' => 'بالاو - Palau', 'code' => 'PW'],
            ['name' => 'فلسطين - Palestine', 'code' => 'PS'],
            ['name' => 'بنما - Panama', 'code' => 'PA'],
            ['name' => 'بابوا غينيا الجديدة - Papua New Guinea', 'code' => 'PG'],
            ['name' => 'باراغواي - Paraguay', 'code' => 'PY'],
            ['name' => 'بيرو - Peru', 'code' => 'PE'],
            ['name' => 'الفلبين - Philippines', 'code' => 'PH'],
            ['name' => 'بولندا - Poland', 'code' => 'PL'],
            ['name' => 'البرتغال - Portugal', 'code' => 'PT'],
            ['name' => 'قطر - Qatar', 'code' => 'QA'],
            ['name' => 'رومانيا - Romania', 'code' => 'RO'],
            ['name' => 'روسيا - Russia', 'code' => 'RU'],
            ['name' => 'رواندا - Rwanda', 'code' => 'RW'],
            ['name' => 'سانت كيتس ونيفيس - Saint Kitts and Nevis', 'code' => 'KN'],
            ['name' => 'سانت لوسيا - Saint Lucia', 'code' => 'LC'],
            ['name' => 'سانت فنسنت والغرينادين - Saint Vincent and the Grenadines', 'code' => 'VC'],
            ['name' => 'ساموا - Samoa', 'code' => 'WS'],
            ['name' => 'سان مارينو - San Marino', 'code' => 'SM'],
            ['name' => 'ساو تومي وبرينسيبي - Sao Tome and Principe', 'code' => 'ST'],
            ['name' => 'السعودية - Saudi Arabia', 'code' => 'SA'],
            ['name' => 'السنغال - Senegal', 'code' => 'SN'],
            ['name' => 'صربيا - Serbia', 'code' => 'RS'],
            ['name' => 'سيشل - Seychelles', 'code' => 'SC'],
            ['name' => 'سيراليون - Sierra Leone', 'code' => 'SL'],
            ['name' => 'سنغافورة - Singapore', 'code' => 'SG'],
            ['name' => 'سلوفاكيا - Slovakia', 'code' => 'SK'],
            ['name' => 'سلوفينيا - Slovenia', 'code' => 'SI'],
            ['name' => 'جزر سليمان - Solomon Islands', 'code' => 'SB'],
            ['name' => 'الصومال - Somalia', 'code' => 'SO'],
            ['name' => 'جنوب أفريقيا - South Africa', 'code' => 'ZA'],
            ['name' => 'كوريا الجنوبية - South Korea', 'code' => 'KR'],
            ['name' => 'جنوب السودان - South Sudan', 'code' => 'SS'],
            ['name' => 'إسبانيا - Spain', 'code' => 'ES'],
            ['name' => 'سريلانكا - Sri Lanka', 'code' => 'LK'],
            ['name' => 'السودان - Sudan', 'code' => 'SD'],
            ['name' => 'سورينام - Suriname', 'code' => 'SR'],
            ['name' => 'السويد - Sweden', 'code' => 'SE'],
            ['name' => 'سويسرا - Switzerland', 'code' => 'CH'],
            ['name' => 'سوريا - Syria', 'code' => 'SY'],
            ['name' => 'طاجيكستان - Tajikistan', 'code' => 'TJ'],
            ['name' => 'تنزانيا - Tanzania', 'code' => 'TZ'],
            ['name' => 'تايلاند - Thailand', 'code' => 'TH'],
            ['name' => 'تيمور الشرقية - East Timor', 'code' => 'TL'],
            ['name' => 'توغو - Togo', 'code' => 'TG'],
            ['name' => 'تونغا - Tonga', 'code' => 'TO'],
            ['name' => 'ترينيداد وتوباغو - Trinidad and Tobago', 'code' => 'TT'],
            ['name' => 'تونس - Tunisia', 'code' => 'TN'],
            ['name' => 'تركيا - Türkiye', 'code' => 'TR'],
            ['name' => 'تركمانستان - Turkmenistan', 'code' => 'TM'],
            ['name' => 'توفالو - Tuvalu', 'code' => 'TV'],
            ['name' => 'أوغندا - Uganda', 'code' => 'UG'],
            ['name' => 'أوكرانيا - Ukraine', 'code' => 'UA'],
            ['name' => 'الإمارات العربية المتحدة - United Arab Emirates', 'code' => 'AE'],
            ['name' => 'المملكة المتحدة - United Kingdom', 'code' => 'GB'],
            ['name' => 'الولايات المتحدة - United States', 'code' => 'US'],
            ['name' => 'أوروغواي - Uruguay', 'code' => 'UY'],
            ['name' => 'أوزبكستان - Uzbekistan', 'code' => 'UZ'],
            ['name' => 'فانواتو - Vanuatu', 'code' => 'VU'],
            ['name' => 'الفاتيكان - Vatican', 'code' => 'VA'],
            ['name' => 'فنزويلا - Venezuela', 'code' => 'VE'],
            ['name' => 'فيتنام - Vietnam', 'code' => 'VN'],
            ['name' => 'اليمن - Yemen', 'code' => 'YE'],
            ['name' => 'زامبيا - Zambia', 'code' => 'ZM'],
            ['name' => 'زيمبابوي - Zimbabwe', 'code' => 'ZW'],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->updateOrInsert(
                ['code' => $country['code']],
                [
                    'name' => $country['name'],
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }
}
