<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $languages = [
            ['name' => 'العربية', 'code' => 'ar'],
            ['name' => 'الإنجليزية', 'code' => 'en'],
            ['name' => 'الفرنسية', 'code' => 'fr'],
            ['name' => 'الألمانية', 'code' => 'de'],
            ['name' => 'الإسبانية', 'code' => 'es'],
            ['name' => 'الإيطالية', 'code' => 'it'],
            ['name' => 'البرتغالية', 'code' => 'pt'],
            ['name' => 'الروسية', 'code' => 'ru'],
            ['name' => 'الصينية', 'code' => 'zh'],
            ['name' => 'اليابانية', 'code' => 'ja'],
            ['name' => 'الكورية', 'code' => 'ko'],
            ['name' => 'التركية', 'code' => 'tr'],
            ['name' => 'الفارسية', 'code' => 'fa'],
            ['name' => 'العبرية', 'code' => 'he'],
            ['name' => 'الأردية', 'code' => 'ur'],
            ['name' => 'الهندية', 'code' => 'hi'],
            ['name' => 'البنغالية', 'code' => 'bn'],
            ['name' => 'الإندونيسية', 'code' => 'id'],
            ['name' => 'الماليزية', 'code' => 'ms'],
            ['name' => 'الهولندية', 'code' => 'nl'],
            ['name' => 'السويدية', 'code' => 'sv'],
            ['name' => 'النرويجية', 'code' => 'no'],
            ['name' => 'الدنماركية', 'code' => 'da'],
            ['name' => 'الفنلندية', 'code' => 'fi'],
            ['name' => 'البولندية', 'code' => 'pl'],
            ['name' => 'الأوكرانية', 'code' => 'uk'],
            ['name' => 'اليونانية', 'code' => 'el'],
            ['name' => 'الرومانية', 'code' => 'ro'],
            ['name' => 'التشيكية', 'code' => 'cs'],
            ['name' => 'السلوفاكية', 'code' => 'sk'],
            ['name' => 'البلغارية', 'code' => 'bg'],
            ['name' => 'الصربية', 'code' => 'sr'],
            ['name' => 'الكرواتية', 'code' => 'hr'],
            ['name' => 'البوسنية', 'code' => 'bs'],
            ['name' => 'الألبانية', 'code' => 'sq'],
            ['name' => 'المجرية', 'code' => 'hu'],
            ['name' => 'اللاتفية', 'code' => 'lv'],
            ['name' => 'الليتوانية', 'code' => 'lt'],
            ['name' => 'الإستونية', 'code' => 'et'],
            ['name' => 'الأيسلندية', 'code' => 'is'],
            ['name' => 'الأيرلندية', 'code' => 'ga'],
            ['name' => 'الويلزية', 'code' => 'cy'],
            ['name' => 'الكتالونية', 'code' => 'ca'],
            ['name' => 'الباسكية', 'code' => 'eu'],
            ['name' => 'الجاليكية', 'code' => 'gl'],
            ['name' => 'الأرمينية', 'code' => 'hy'],
            ['name' => 'الجورجية', 'code' => 'ka'],
            ['name' => 'الأذربيجانية', 'code' => 'az'],
            ['name' => 'الكازاخية', 'code' => 'kk'],
            ['name' => 'الأوزبكية', 'code' => 'uz'],
            ['name' => 'التركمانية', 'code' => 'tk'],
            ['name' => 'القيرغيزية', 'code' => 'ky'],
            ['name' => 'الطاجيكية', 'code' => 'tg'],
            ['name' => 'البشتوية', 'code' => 'ps'],
            ['name' => 'الكردية', 'code' => 'ku'],
            ['name' => 'النيبالية', 'code' => 'ne'],
            ['name' => 'السنهالية', 'code' => 'si'],
            ['name' => 'التاميلية', 'code' => 'ta'],
            ['name' => 'التيلوغوية', 'code' => 'te'],
            ['name' => 'المالايالامية', 'code' => 'ml'],
            ['name' => 'الكانادية', 'code' => 'kn'],
            ['name' => 'الماراثية', 'code' => 'mr'],
            ['name' => 'الغوجاراتية', 'code' => 'gu'],
            ['name' => 'البنجابية', 'code' => 'pa'],
            ['name' => 'الأسامية', 'code' => 'as'],
            ['name' => 'الأوريا', 'code' => 'or'],
            ['name' => 'البورمية', 'code' => 'my'],
            ['name' => 'التايلاندية', 'code' => 'th'],
            ['name' => 'الفيتنامية', 'code' => 'vi'],
            ['name' => 'الخميرية', 'code' => 'km'],
            ['name' => 'اللاوية', 'code' => 'lo'],
            ['name' => 'المنغولية', 'code' => 'mn'],
            ['name' => 'التبتية', 'code' => 'bo'],

            ['name' => 'الأفريكانية', 'code' => 'af'],
            ['name' => 'الأمهرية', 'code' => 'am'],
            ['name' => 'الصومالية', 'code' => 'so'],
            ['name' => 'السواحيلية', 'code' => 'sw'],
            ['name' => 'الهوسا', 'code' => 'ha'],
            ['name' => 'اليوروبا', 'code' => 'yo'],
            ['name' => 'الإيغبو', 'code' => 'ig'],
            ['name' => 'الزولو', 'code' => 'zu'],
            ['name' => 'الخوسا', 'code' => 'xh'],
            ['name' => 'الملغاشية', 'code' => 'mg'],

            ['name' => 'الأفارية', 'code' => 'av'],
            ['name' => 'الأبخازية', 'code' => 'ab'],
            ['name' => 'الأفارية الإثيوبية', 'code' => 'aa'],
            ['name' => 'الأكانية', 'code' => 'ak'],
            ['name' => 'الأراغونية', 'code' => 'an'],
            ['name' => 'الأفستية', 'code' => 'ae'],
            ['name' => 'الأيمرية', 'code' => 'ay'],
            ['name' => 'الباشكيرية', 'code' => 'ba'],
            ['name' => 'البيلاروسية', 'code' => 'be'],
            ['name' => 'البيهارية', 'code' => 'bh'],
            ['name' => 'البيسلاما', 'code' => 'bi'],
            ['name' => 'البامبارا', 'code' => 'bm'],
            ['name' => 'البريتونية', 'code' => 'br'],
            ['name' => 'الشيشانية', 'code' => 'ce'],
            ['name' => 'التشامورو', 'code' => 'ch'],
            ['name' => 'الكورسيكية', 'code' => 'co'],
            ['name' => 'الكري', 'code' => 'cr'],
            ['name' => 'السلافونية الكنسية', 'code' => 'cu'],
            ['name' => 'التشوفاشية', 'code' => 'cv'],
            ['name' => 'الديفيهية', 'code' => 'dv'],
            ['name' => 'الدزونكا', 'code' => 'dz'],
            ['name' => 'الإيوي', 'code' => 'ee'],
            ['name' => 'الإسبرانتو', 'code' => 'eo'],
            ['name' => 'الفولانية', 'code' => 'ff'],
            ['name' => 'الفيجية', 'code' => 'fj'],
            ['name' => 'الفاروية', 'code' => 'fo'],
            ['name' => 'الفريزية الغربية', 'code' => 'fy'],
            ['name' => 'الغيلية الاسكتلندية', 'code' => 'gd'],
            ['name' => 'الغوارانية', 'code' => 'gn'],
            ['name' => 'المانكسية', 'code' => 'gv'],
            ['name' => 'الهيري موتو', 'code' => 'ho'],
            ['name' => 'الكريولية الهايتية', 'code' => 'ht'],
            ['name' => 'الهيريرو', 'code' => 'hz'],
            ['name' => 'إنترلينغوا', 'code' => 'ia'],
            ['name' => 'إنترلينغ', 'code' => 'ie'],
            ['name' => 'السيتشوان يي', 'code' => 'ii'],
            ['name' => 'الإينوبياكية', 'code' => 'ik'],
            ['name' => 'الإيدو', 'code' => 'io'],
            ['name' => 'الإينكتيتوتية', 'code' => 'iu'],
            ['name' => 'الجاوية', 'code' => 'jv'],
            ['name' => 'الكونغو', 'code' => 'kg'],
            ['name' => 'الكيكويو', 'code' => 'ki'],
            ['name' => 'الكوانياما', 'code' => 'kj'],
            ['name' => 'الغرينلاندية', 'code' => 'kl'],
            ['name' => 'الكانورية', 'code' => 'kr'],
            ['name' => 'الكشميرية', 'code' => 'ks'],
            ['name' => 'الكومية', 'code' => 'kv'],
            ['name' => 'الكورنية', 'code' => 'kw'],
            ['name' => 'اللاتينية', 'code' => 'la'],
            ['name' => 'اللوكسمبورغية', 'code' => 'lb'],
            ['name' => 'الغاندا', 'code' => 'lg'],
            ['name' => 'الليمبورغية', 'code' => 'li'],
            ['name' => 'اللينغالا', 'code' => 'ln'],
            ['name' => 'اللوبا كاتانغا', 'code' => 'lu'],
            ['name' => 'المارشالية', 'code' => 'mh'],
            ['name' => 'الماورية', 'code' => 'mi'],
            ['name' => 'المقدونية', 'code' => 'mk'],
            ['name' => 'المالطية', 'code' => 'mt'],
            ['name' => 'الناوروية', 'code' => 'na'],
            ['name' => 'النرويجية بوكمال', 'code' => 'nb'],
            ['name' => 'النديبيلي الشمالية', 'code' => 'nd'],
            ['name' => 'الندونغا', 'code' => 'ng'],
            ['name' => 'النرويجية نينوشك', 'code' => 'nn'],
            ['name' => 'النديبيلي الجنوبية', 'code' => 'nr'],
            ['name' => 'النافاهو', 'code' => 'nv'],
            ['name' => 'الشيشيوا', 'code' => 'ny'],
            ['name' => 'الأوكسيتانية', 'code' => 'oc'],
            ['name' => 'الأوجيبوا', 'code' => 'oj'],
            ['name' => 'الأورومو', 'code' => 'om'],
            ['name' => 'الأوسيتية', 'code' => 'os'],
            ['name' => 'البالية', 'code' => 'pi'],
            ['name' => 'الكيتشوا', 'code' => 'qu'],
            ['name' => 'الرومانشية', 'code' => 'rm'],
            ['name' => 'الكيروندية', 'code' => 'rn'],
            ['name' => 'الكينيارواندية', 'code' => 'rw'],
            ['name' => 'السنسكريتية', 'code' => 'sa'],
            ['name' => 'السردينية', 'code' => 'sc'],
            ['name' => 'السندية', 'code' => 'sd'],
            ['name' => 'السامي الشمالية', 'code' => 'se'],
            ['name' => 'السانغو', 'code' => 'sg'],
            ['name' => 'الساموية', 'code' => 'sm'],
            ['name' => 'الشونا', 'code' => 'sn'],
            ['name' => 'السوتو الجنوبية', 'code' => 'st'],
            ['name' => 'السوندانية', 'code' => 'su'],
            ['name' => 'السوازية', 'code' => 'ss'],
            ['name' => 'التسوانية', 'code' => 'tn'],
            ['name' => 'التونغية', 'code' => 'to'],
            ['name' => 'التسونغا', 'code' => 'ts'],
            ['name' => 'التترية', 'code' => 'tt'],
            ['name' => 'التوي', 'code' => 'tw'],
            ['name' => 'التاهيتية', 'code' => 'ty'],
            ['name' => 'الأويغورية', 'code' => 'ug'],
            ['name' => 'الفيندية', 'code' => 've'],
            ['name' => 'الفولابوك', 'code' => 'vo'],
            ['name' => 'الوالونية', 'code' => 'wa'],
            ['name' => 'الولوف', 'code' => 'wo'],
            ['name' => 'اليديشية', 'code' => 'yi'],
            ['name' => 'التشوانغ', 'code' => 'za'],
        ];

        $languages = array_map(function ($language) use ($now) {
            return [
                'name' => $language['name'],
                'code' => $language['code'],
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $languages);

        DB::table('languages')->upsert(
            $languages,
            ['code'],
            ['name', 'is_active', 'updated_at']
        );
    }
}
