<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $languages = [
            ['name' => 'العربية - Arabic', 'code' => 'ar'],
            ['name' => 'الإنجليزية - English', 'code' => 'en'],
            ['name' => 'الفرنسية - French', 'code' => 'fr'],
            ['name' => 'الألمانية - German', 'code' => 'de'],
            ['name' => 'الإسبانية - Spanish', 'code' => 'es'],
            ['name' => 'الإيطالية - Italian', 'code' => 'it'],
            ['name' => 'البرتغالية - Portuguese', 'code' => 'pt'],
            ['name' => 'الروسية - Russian', 'code' => 'ru'],
            ['name' => 'الصينية - Chinese', 'code' => 'zh'],
            ['name' => 'اليابانية - Japanese', 'code' => 'ja'],
            ['name' => 'الكورية - Korean', 'code' => 'ko'],
            ['name' => 'التركية - Turkish', 'code' => 'tr'],
            ['name' => 'الفارسية - Persian', 'code' => 'fa'],
            ['name' => 'العبرية - Hebrew', 'code' => 'he'],
            ['name' => 'الأردية - Urdu', 'code' => 'ur'],
            ['name' => 'الهندية - Hindi', 'code' => 'hi'],
            ['name' => 'البنغالية - bangla', 'code' => 'bn'],
            ['name' => 'الإندونيسية - Indonesian', 'code' => 'id'],
            ['name' => 'الماليزية - Malaysian', 'code' => 'ms'],
            ['name' => 'الهولندية - Dutch', 'code' => 'nl'],
            ['name' => 'السويدية - Swedish', 'code' => 'sv'],
            ['name' => 'النرويجية - Norwegian', 'code' => 'no'],
            ['name' => 'الدنماركية - Danish', 'code' => 'da'],
            ['name' => 'الفنلندية - Finnish', 'code' => 'fi'],
            ['name' => 'البولندية - Polish', 'code' => 'pl'],
            ['name' => 'الأوكرانية - Ukrainian', 'code' => 'uk'],
            ['name' => 'اليونانية - Greek', 'code' => 'el'],
            ['name' => 'الرومانية - Romanian', 'code' => 'ro'],
            ['name' => 'التشيكية - Czech', 'code' => 'cs'],
            ['name' => 'السلوفاكية - Slovak', 'code' => 'sk'],
            ['name' => 'البلغارية - Bulgarian', 'code' => 'bg'],
            ['name' => 'الصربية - Serbian', 'code' => 'sr'],
            ['name' => 'الكرواتية - Croatian', 'code' => 'hr'],
            ['name' => 'البوسنية - Bosnian', 'code' => 'bs'],
            ['name' => 'الألبانية - Albanian', 'code' => 'sq'],
            ['name' => 'المجرية - Hungarian', 'code' => 'hu'],
            ['name' => 'اللاتفية - Latvian', 'code' => 'lv'],
            ['name' => 'الليتوانية - Lithuanian', 'code' => 'lt'],
            ['name' => 'الإستونية - Estonian', 'code' => 'et'],
            ['name' => 'الأيسلندية - Icelandic', 'code' => 'is'],
            ['name' => 'الأيرلندية - Irish', 'code' => 'ga'],
            ['name' => 'الويلزية - Welsh', 'code' => 'cy'],
            ['name' => 'الكتالونية - Catalan', 'code' => 'ca'],
            ['name' => 'الباسكية - Basque', 'code' => 'eu'],
            ['name' => 'الجاليكية - Galician', 'code' => 'gl'],
            ['name' => 'الأرمينية - Armenian', 'code' => 'hy'],
            ['name' => 'الجورجية - Georgian', 'code' => 'ka'],
            ['name' => 'الأذربيجانية - Azerbaijani', 'code' => 'az'],
            ['name' => 'الكازاخية - Kazakh', 'code' => 'kk'],
            ['name' => 'الأوزبكية - Uzbek', 'code' => 'uz'],
            ['name' => 'التركمانية - Turkmen', 'code' => 'tk'],
            ['name' => 'القيرغيزية - Kyrgyz', 'code' => 'ky'],
            ['name' => 'الطاجيكية - Tajik', 'code' => 'tg'],
            ['name' => 'البشتوية - Pashto', 'code' => 'ps'],
            ['name' => 'الكردية - Kurdish', 'code' => 'ku'],
            ['name' => 'النيبالية - Nepali', 'code' => 'ne'],
            ['name' => 'السنهالية - Sinhala', 'code' => 'si'],
            ['name' => 'التاميلية - Tamil', 'code' => 'ta'],
            ['name' => 'التيلوغوية - Telugu', 'code' => 'te'],
            ['name' => 'المالايالامية - Malayalam', 'code' => 'ml'],
            ['name' => 'الكانادية - Kannada', 'code' => 'kn'],
            ['name' => 'الماراثية - Marathi', 'code' => 'mr'],
            ['name' => 'الغوجاراتية - Gujarati', 'code' => 'gu'],
            ['name' => 'البنجابية - Punjabi', 'code' => 'pa'],
            ['name' => 'الأسامية - Assamese', 'code' => 'as'],
            ['name' => 'الأوريا - Oriya', 'code' => 'or'],
            ['name' => 'البورمية - Burmese', 'code' => 'my'],
            ['name' => 'التايلاندية - Thai', 'code' => 'th'],
            ['name' => 'الفيتنامية - Vietnamese', 'code' => 'vi'],
            ['name' => 'الخميرية - Khmer', 'code' => 'km'],
            ['name' => 'اللاوية - Leviticus', 'code' => 'lo'],
            ['name' => 'المنغولية - Mongolian', 'code' => 'mn'],
            ['name' => 'التبتية - Tibetan', 'code' => 'bo'],
            ['name' => 'الأفريكانية - Afrikaans', 'code' => 'af'],
            ['name' => 'الأمهرية - Amharic', 'code' => 'am'],
            ['name' => 'الصومالية - Somali', 'code' => 'so'],
            ['name' => 'السواحيلية - Swahili', 'code' => 'sw'],
            ['name' => 'الهوسا - Hausa', 'code' => 'ha'],
            ['name' => 'اليوروبا - Yoruba', 'code' => 'yo'],
            ['name' => 'الإيغبو - Igbo', 'code' => 'ig'],
            ['name' => 'الزولو - Zulu', 'code' => 'zu'],
            ['name' => 'الخوسا - Xhosa', 'code' => 'xh'],
            ['name' => 'الملغاشية - Malagasy', 'code' => 'mg'],
            ['name' => 'الأفارية - Avarian', 'code' => 'av'],
            ['name' => 'الأبخازية - Abkhazian', 'code' => 'ab'],
            ['name' => 'الأفارية الإثيوبية - Ethiopian Avarian', 'code' => 'aa'],
            ['name' => 'الأكانية - Akan', 'code' => 'ak'],
            ['name' => 'الأراغونية - Aragonese', 'code' => 'an'],
            ['name' => 'الأفستية - Avestan', 'code' => 'ae'],
            ['name' => 'الأيمرية - Eimeria', 'code' => 'ay'],
            ['name' => 'الباشكيرية - Bashkir', 'code' => 'ba'],
            ['name' => 'البيلاروسية - Belarusian', 'code' => 'be'],
            ['name' => 'البيهارية - Bihari', 'code' => 'bh'],
            ['name' => 'البيسلاما - Bislama', 'code' => 'bi'],
            ['name' => 'البامبارا - Bambara', 'code' => 'bm'],
            ['name' => 'البريتونية - Peritoneum', 'code' => 'br'],
            ['name' => 'الشيشانية - Chechen', 'code' => 'ce'],
            ['name' => 'التشامورو - Chamorro', 'code' => 'ch'],
            ['name' => 'الكورسيكية - Corsican', 'code' => 'co'],
            ['name' => 'الكري - Cree', 'code' => 'cr'],
            ['name' => 'السلافونية الكنسية - Church Slavonic', 'code' => 'cu'],
            ['name' => 'التشوفاشية - Chuvashism', 'code' => 'cv'],
            ['name' => 'الديفيهية - Dhivehi', 'code' => 'dv'],
            ['name' => 'الدزونكا - Dzhunka', 'code' => 'dz'],
            ['name' => 'الإيوي - The Ewe', 'code' => 'ee'],
            ['name' => 'الإسبرانتو - Esperanto', 'code' => 'eo'],
            ['name' => 'الفولانية - Fulani', 'code' => 'ff'],
            ['name' => 'الفيجية - Fijian', 'code' => 'fj'],
            ['name' => 'الفاروية - Faroese', 'code' => 'fo'],
            ['name' => 'الفريزية الغربية - West Frisian', 'code' => 'fy'],
            ['name' => 'الغيلية الاسكتلندية - Scottish Gaelic', 'code' => 'gd'],
            ['name' => 'الغوارانية - Guarani', 'code' => 'gn'],
            ['name' => 'المانكسية - Manxism', 'code' => 'gv'],
            ['name' => 'الهيري موتو - Heri Moto', 'code' => 'ho'],
            ['name' => 'الكريولية الهايتية - Haitian Creole', 'code' => 'ht'],
            ['name' => 'الهيريرو - Herero', 'code' => 'hz'],
            ['name' => 'إنترلينغوا - Interlingua', 'code' => 'ia'],
            ['name' => 'إنترلينغ - Interling', 'code' => 'ie'],
            ['name' => 'السيتشوان يي - Sichuan Yi', 'code' => 'ii'],
            ['name' => 'الإينوبياكية - Iñupiaq', 'code' => 'ik'],
            ['name' => 'الإيدو - Edo', 'code' => 'io'],
            ['name' => 'الإينكتيتوتية - Inuktitutism', 'code' => 'iu'],
            ['name' => 'الجاوية - Javanese', 'code' => 'jv'],
            ['name' => 'الكونغو - Congo', 'code' => 'kg'],
            ['name' => 'الكيكويو - Kikuyu', 'code' => 'ki'],
            ['name' => 'الكوانياما - Kwanyama', 'code' => 'kj'],
            ['name' => 'الغرينلاندية - Greenlandic', 'code' => 'kl'],
            ['name' => 'الكانورية - Canorian', 'code' => 'kr'],
            ['name' => 'الكشميرية - Kashmiri', 'code' => 'ks'],
            ['name' => 'الكومية - The pile', 'code' => 'kv'],
            ['name' => 'الكورنية - Cornish', 'code' => 'kw'],
            ['name' => 'اللاتينية - Latin', 'code' => 'la'],
            ['name' => 'اللوكسمبورغية - Luxembourgish', 'code' => 'lb'],
            ['name' => 'الغاندا - Ganda', 'code' => 'lg'],
            ['name' => 'الليمبورغية - Limburgian', 'code' => 'li'],
            ['name' => 'اللينغالا - Lingala', 'code' => 'ln'],
            ['name' => 'اللوبا كاتانغا - Luba Katanga', 'code' => 'lu'],
            ['name' => 'المارشالية - Marshallese', 'code' => 'mh'],
            ['name' => 'الماورية - Māori', 'code' => 'mi'],
            ['name' => 'المقدونية - Macedonian', 'code' => 'mk'],
            ['name' => 'المالطية - Maltese', 'code' => 'mt'],
            ['name' => 'الناوروية - Nauruan', 'code' => 'na'],
            ['name' => 'النرويجية بوكمال - Norwegian Bokmal', 'code' => 'nb'],
            ['name' => 'النديبيلي الشمالية - Northern Ndebele', 'code' => 'nd'],
            ['name' => 'الندونغا - Ndonga', 'code' => 'ng'],
            ['name' => 'النرويجية نينوشك - Norwegian nynoshk', 'code' => 'nn'],
            ['name' => 'النديبيلي الجنوبية - Southern Ndebele', 'code' => 'nr'],
            ['name' => 'النافاهو - Navajo', 'code' => 'nv'],
            ['name' => 'الشيشيوا - Chichewa', 'code' => 'ny'],
            ['name' => 'الأوكسيتانية - Occitan', 'code' => 'oc'],
            ['name' => 'الأوجيبوا - Ojibwa', 'code' => 'oj'],
            ['name' => 'الأورومو - Oromo', 'code' => 'om'],
            ['name' => 'الأوسيتية - Ossetian', 'code' => 'os'],
            ['name' => 'البالية - worn out', 'code' => 'pi'],
            ['name' => 'الكيتشوا - Quechua', 'code' => 'qu'],
            ['name' => 'الرومانشية - Romansh', 'code' => 'rm'],
            ['name' => 'الكيروندية - Kirundism', 'code' => 'rn'],
            ['name' => 'الكينيارواندية - Kinyarwanda', 'code' => 'rw'],
            ['name' => 'السنسكريتية - Sanskrit', 'code' => 'sa'],
            ['name' => 'السردينية - Sardinian', 'code' => 'sc'],
            ['name' => 'السندية - Sindhi', 'code' => 'sd'],
            ['name' => 'السامي الشمالية - Northern Sami', 'code' => 'se'],
            ['name' => 'السانغو - Sango', 'code' => 'sg'],
            ['name' => 'الساموية - Samoan', 'code' => 'sm'],
            ['name' => 'الشونا - Shona', 'code' => 'sn'],
            ['name' => 'السوتو الجنوبية - Southern Sotho', 'code' => 'st'],
            ['name' => 'السوندانية - Sundanese', 'code' => 'su'],
            ['name' => 'السوازية - Swazi', 'code' => 'ss'],
            ['name' => 'التسوانية - Tswana', 'code' => 'tn'],
            ['name' => 'التونغية - Tongan', 'code' => 'to'],
            ['name' => 'التسونغا - Tsonga', 'code' => 'ts'],
            ['name' => 'التترية - Tatar', 'code' => 'tt'],
            ['name' => 'التوي - Twi', 'code' => 'tw'],
            ['name' => 'التاهيتية - Tahitian', 'code' => 'ty'],
            ['name' => 'الأويغورية - Uyghur', 'code' => 'ug'],
            ['name' => 'الفيندية - Vendism', 'code' => 've'],
            ['name' => 'الفولابوك - Volapok', 'code' => 'vo'],
            ['name' => 'الوالونية - Wallonia', 'code' => 'wa'],
            ['name' => 'الولوف - Wolof', 'code' => 'wo'],
            ['name' => 'اليديشية - Yiddish', 'code' => 'yi'],
            ['name' => 'التشوانغ - Zhuang', 'code' => 'za'],
        ];

        $languages = array_map(function ($language) use ($now) {
            return [
                'name' => $language['name'],
                'code' => $language['code'],
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $languages);

        DB::table('languages')->upsert(
            $languages,
            ['code'],
            ['name', 'is_active', 'updated_at']
        );
    }
}
